version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-{{ .Branch }}
            - npm-packages-
      - run:
          name: Install Dependencies
          command: npm --prefer-offline --no-progress install
      - save_cache:
          name: Save Package Cache
          key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: Run tests
          command: npm --prefer-offline --no-progress run dist-test
      - run:
          name: Build documentation
          command: npm --prefer-offline --no-progress run docs
