version: 2.1

orbs:
  branch-management: opennms/branch-management@2.3.0

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-{{ .Branch }}
            - npm-packages-
      - run:
          name: Install Dependencies
          command: npm --prefer-offline --no-progress install
      - save_cache:
          name: Save Package Cache
          key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: Run tests
          command: npm --prefer-offline --no-progress run dist-test
      - run:
          name: Build documentation
          command: npm --prefer-offline --no-progress run docs
  merge:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - branch-management/merge-branch:
          committer_email: "cicd-system@opennms.com"
          committer_name: "CI/CD System"
          from: develop
          to: main
      - run:
          name: "Push to Main"
          command: git push origin

workflows:
  build-and-merge:
    jobs:
      - build
      - merge:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - ranger/docs