name: OpenNMS-JS Build
run-name: Build and Test the application
on:
  workflow_dispatch:
  push:
    tags-ignore:
  pull_request:
    branches-ignore:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: |
          npm ci
      - name: Full build
        run: |
          npm run full
